SELECT state.capital FROM state WHERE state.state_name IN (SELECT border_info.border FROM border_info WHERE border_info.state_name IN (SELECT border_info.border FROM border_info WHERE border_info.state_name = 'texas'));;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='new mexico');;
SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state WHERE state.state_name IN (SELECT border_info.border FROM border_info WHERE border_info.state_name = 'texas') ) AND state.state_name IN ((SELECT border_info.border FROM border_info WHERE border_info.state_name = 'texas'));;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='ohio') AND state.area=(SELECT min(state.area) FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='ohio' ));;
SELECT count(river.river_name) FROM river WHERE river.traverse IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='colorado');;
SELECT city.population FROM city WHERE city.city_name=(SELECT state.capital FROM state WHERE state.state_name = 'texas');;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city,state WHERE city.city_name=state.capital);;
SELECT lake.lake_name FROM lake WHERE lake.state_name IN (SELECT border_info.border FROM border_info WHERE border_info.state_name = 'texas');;
SELECT highlow.state_name FROM highlow WHERE highlow.lowest_elevation=(SELECT min(highlow.lowest_elevation) FROM highlow,river WHERE(river.river_name='mississippi') AND(river.traverse=highlow.state_name));;
SELECT river.river_name FROM river WHERE river.traverse IN ( SELECT highlow.state_name FROM highlow WHERE highlow.lowest_elevation=(SELECT min(highlow.lowest_elevation) FROM highlow));;
SELECT city.city_name FROM city WHERE city.state_name IN(SELECT border_info.state_name FROM border_info WHERE border_info.border='california') AND city.population=(SELECT max(city.population) FROM city WHERE city.state_name IN(SELECT border_info.state_name FROM border_info WHERE border_info.border='california'));;
SELECT river.river_name FROM river,highlow WHERE river.traverse=highlow.state_name AND highlow.highest_elevation=(SELECT max(highlow.highest_elevation) FROM highlow) ORDER BY river.length DESC LIMIT 1;;
SELECT river.traverse FROM river,state WHERE river.traverse=state.state_name GROUP BY state.state_name ORDER BY count(river.river_name) DESC LIMIT 1 ;;
SELECT sum(state.population) FROM state ,border_info WHERE state.state_name=border_info.border AND border_info.state_name='texas';;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city,state WHERE city.city_name=state.capital);;
SELECT state.state_name FROM state WHERE state.state_name NOT IN(SELECT border_info.state_name FROM border_info);;
SELECT highlow.highest_point FROM highlow,state WHERE highlow.state_name=state.state_name AND state.state_name IN(SELECT state.state_name FROM state WHERE state.area=(SELECT max(state.area) FROM state));;
SELECT state.population FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT border_info.border FROM border_info WHERE border_info.state_name IN ( SELECT tmp1.state_name FROM (SELECT city.state_name, count(1) AS cnt1 FROM city GROUP BY city.state_name) tmp1 WHERE cnt1 = (SELECT max(cnt) FROM (SELECT count(1) AS cnt FROM city GROUP BY city.state_name) tmp));
SELECT state.capital FROM state,border_info WHERE border_info.border=state.state_name AND border_info.state_name='texas';;
SELECT highlow.highest_point FROM highlow WHERE(highlow.state_name=(SELECT river.traverse FROM river,state WHERE river.traverse=state.state_name GROUP BY state.state_name ORDER BY count(river.river_name) DESC LIMIT 1));;
SELECT city.city_name FROM city WHERE city.population=(SELECT min(city.population) FROM city WHERE city.state_name IN(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state))) AND city.state_name IN(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state));;
SELECT highlow.highest_point FROM highlow WHERE highlow.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='mississippi');;
SELECT border_info.border FROM border_info WHERE border_info.state_name IN (SELECT river.traverse FROM river WHERE river.length = (SELECT max(river.length) FROM river)  );;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi') AND state.area=(SELECT max(state.area) FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi'));;
SELECT count(city.city_name) FROM city WHERE city.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='utah') AND city.population>150000;;
SELECT state.population FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.length=(SELECT max(river.length) FROM river)) AND state.area=(SELECT min(state.area) FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.length=(SELECT max(river.length) FROM river)));;
SELECT highlow.lowest_elevation FROM highlow,river WHERE river.river_name='mississippi'  AND river.traverse=highlow.state_name;;
SELECT state.population FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT count(border_info.border) FROM border_info WHERE border_info.state_name=(SELECT state.state_name FROM state WHERE state.capital='boston');;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city,state WHERE city.city_name=state.capital);;
SELECT border_info.border FROM border_info WHERE border_info.state_name IN(SELECT state.state_name FROM state WHERE state.population=(SELECT min(state.population) FROM state));;
SELECT border_info.state_name FROM state,border_info WHERE state.state_name=border_info.border AND state.population=(SELECT max(state.population) FROM state);;
SELECT highlow.highest_point FROM highlow WHERE highlow.state_name IN(SELECT state.state_name FROM state WHERE state.capital='des moines');;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city,state WHERE city.city_name=state.capital);;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas') AND state.area=(SELECT max(state.area) FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas'));;
SELECT city.city_name FROM city WHERE city.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas') AND city.population=(SELECT max(city.population) FROM city WHERE city.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas'));;
SELECT border_info.border FROM border_info WHERE border_info.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT city.state_name FROM city,state WHERE city.state_name=state.state_name AND city.city_name='springfield';;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT border_info.border FROM border_info WHERE border_info.state_name IN(SELECT state.state_name FROM state WHERE state.population=(SELECT max(state.population) FROM state )));;
SELECT state.population FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT count(border_info.border) FROM border_info WHERE border_info.state_name=(SELECT state.state_name FROM state WHERE state.area=(SELECT max(state.area) FROM state));;
(SELECT city.state_name FROM city WHERE city.population = (SELECT min(tmp.population) FROM (SELECT city.population FROM city, state WHERE state.capital = city.city_name) tmp) );;
SELECT city.city_name FROM city WHERE city.population>150000 AND city.state_name=(SELECT state.state_name FROM state WHERE state.area=(SELECT max(state.area) FROM state));;
SELECT state.state_name FROM state left outer join border_info ON state.state_name = border_info.state_name GROUP BY state.state_name having count(border_info.border) = (SELECT min(cnt) FROM (SELECT state.state_name, count(border_info.border) AS cnt FROM state left outer join border_info ON state.state_name = border_info.state_name GROUP BY state.state_name) tmp);;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT border_info.border FROM border_info WHERE border_info.state_name IN(SELECT state.state_name FROM state WHERE state.capital='atlanta'));;
SELECT city.population FROM city WHERE city.city_name=(SELECT state.capital FROM state WHERE state.area=(SELECT max(state.area) FROM state,river WHERE river.traverse=state.state_name AND river.river_name='mississippi'));;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city,state WHERE city.city_name=state.capital);;
SELECT highlow.highest_point FROM highlow,state WHERE highlow.state_name=state.state_name AND state.state_name IN(SELECT state.state_name FROM state WHERE state.population=(SELECT min(state.population) FROM state));;
SELECT border_info.border FROM border_info WHERE border_info.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT city.city_name FROM city WHERE city.population IN (SELECT mx FROM (SELECT state.state_name , max(city.population) AS mx FROM state, city WHERE state.state_name = city.state_name AND state.state_name IN ( SELECT border_info.border FROM border_info GROUP BY border_info.border having count(1) = (SELECT max(cnt1) FROM (SELECT border_info.border, count(1) AS cnt1 FROM border_info GROUP BY border_info.border) tmp1)) GROUP BY state.state_name) tmp2);;
SELECT highlow.highest_point FROM highlow,state WHERE highlow.state_name=state.state_name AND state.area=(SELECT min(state.area) FROM state);;
SELECT count(river.river_name) FROM river WHERE river.traverse NOT IN(SELECT state.state_name FROM state WHERE state.capital='albany');;
SELECT state.state_name FROM state WHERE state.state_name NOT IN (SELECT river.traverse FROM river);;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas') AND state.area=(SELECT min(state.area) FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas' ));;
SELECT city.city_name FROM city WHERE city.population>150000 AND city.state_name=(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state ));;
SELECT state.capital FROM state,highlow WHERE state.state_name=highlow.state_name AND highlow.highest_elevation=(SELECT max(highlow.highest_elevation) FROM highlow);;
SELECT state.state_name FROM state left outer join border_info ON state.state_name = border_info.state_name WHERE state.state_name <> 'alaska' AND state.state_name <> 'hawaii' GROUP BY state.state_name having count(border_info.border) = (SELECT min(cnt) FROM (SELECT state.state_name, count(border_info.border) AS cnt FROM state left outer join border_info ON state.state_name = border_info.state_name WHERE state.state_name <> 'alaska' AND state.state_name <> 'hawaii' GROUP BY state.state_name) tmp);;
SELECT state.capital FROM state,border_info WHERE border_info.border=state.state_name AND border_info.state_name='texas';;
SELECT count(city.city_name) FROM city WHERE city.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='nebraska') AND city.population>150000;;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city WHERE city.state_name IN(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state))) AND city.state_name IN(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state));;
SELECT city.population FROM city WHERE city.city_name=(SELECT state.capital FROM state WHERE state.area=(SELECT max(state.area) FROM state));;
SELECT state.state_name FROM state WHERE state.state_name NOT IN(SELECT border_info.state_name FROM border_info);;
SELECT count(river.river_name) FROM river,highlow WHERE river.traverse=highlow.state_name AND highlow.highest_elevation=(SELECT max(highlow.highest_elevation) FROM highlow);;
SELECT city.population FROM city WHERE city.city_name=(SELECT state.capital FROM state WHERE state.area=(SELECT min(state.area) FROM state));;
SELECT river.river_name FROM river,border_info WHERE river.traverse=border_info.state_name AND border_info.border='tennessee' ORDER BY river.length DESC LIMIT 1;;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT state.state_name FROM state WHERE state.area=(SELECT max(state.area) FROM state));;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT state.state_name FROM state WHERE state.population=(SELECT max(state.population) FROM state));;
SELECT state.population FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas') AND state.area=(SELECT max(state.area) FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas' ));;
SELECT state.population FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='wyoming') AND state.population=(SELECT max(state.population) FROM state WHERE state.state_name IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='wyoming' ));;
SELECT count(river.river_name) FROM river,state WHERE river.traverse=state.state_name AND state.state_name=(SELECT state.state_name FROM state WHERE state.population=(SELECT max(state.population) FROM state ));;
SELECT state.capital FROM state, city WHERE state.capital = city.city_name AND city.population <= 150000;;
SELECT count(distinct border_info.border) FROM border_info WHERE border_info.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT state.capital FROM state,border_info WHERE border_info.border=state.state_name AND border_info.state_name='texas';;
SELECT highlow.lowest_point FROM highlow,state WHERE highlow.state_name=state.state_name AND state.state_name IN(SELECT state.state_name FROM state WHERE state.area=(SELECT max(state.area) FROM state));;
SELECT state.state_name FROM state WHERE state.state_name NOT IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='texas');;
SELECT highlow.highest_point FROM highlow WHERE highlow.state_name IN(SELECT state.state_name FROM state WHERE state.capital='des moines');;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='rio grande') AND state.area=(SELECT max(state.area) FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='rio grande'));;
SELECT city.city_name FROM city WHERE city.population>150000 AND city.state_name IN (SELECT river.traverse FROM river WHERE river.river_name IN (SELECT river.river_name FROM river WHERE river.traverse='virginia' AND river.length>750) );;
SELECT state.population FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT state.state_name FROM state WHERE state.state_name IN (SELECT river.traverse FROM river WHERE river.river_name = 'mississippi' ) ORDER BY state.population DESC LIMIT 1;;
SELECT border_info.state_name FROM state,border_info,highlow WHERE(state.state_name=border_info.border)AND(border_info.border=highlow.state_name) AND highlow.lowest_elevation=(SELECT min(highlow.lowest_elevation) FROM highlow) ORDER BY state.area DESC LIMIT 1;;
SELECT distinct state.state_name FROM border_info,state WHERE border_info.state_name='oklahoma' AND state.state_name=border_info.border AND state.population=(SELECT max(state.population) FROM border_info,state WHERE border_info.state_name='oklahoma' AND state.state_name=border_info.border);;
SELECT state.state_name FROM state, highlow WHERE state.capital = highlow.highest_point;;
SELECT state.state_name FROM border_info,state WHERE state.state_name=border_info.border AND border_info.state_name='california' AND state.area=(SELECT max(state.area) FROM border_info,state WHERE state.state_name=border_info.border AND border_info.state_name='california');;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state)) AND river.length=(SELECT max(river.length) FROM river WHERE river.traverse IN(SELECT state.state_name FROM state WHERE state.area=(SELECT min(state.area) FROM state)));;
SELECT b1.border FROM border_info b1, border_info b2 WHERE b1.state_name = b2.border AND b2.state_name IN (SELECT state.state_name FROM state WHERE state.population = (SELECT max(state.population) FROM state));;
SELECT state.state_name FROM state WHERE state.state_name IN (SELECT border_info.border FROM border_info WHERE border_info.state_name = 'texas' ) ORDER BY state.population DESC LIMIT 1;;
SELECT highlow.highest_elevation FROM highlow,state WHERE highlow.state_name=state.state_name AND state.area=(SELECT max(state.area) FROM state);;
SELECT state.capital FROM state WHERE state.state_name IN ( SELECT border_info.border FROM border_info GROUP BY border_info.border having count(1) = (SELECT max(cnt1) FROM (SELECT border_info.border, count(1) AS cnt1 FROM border_info GROUP BY border_info.border) tmp) );;
SELECT city.city_name FROM city WHERE city.population=(SELECT max(city.population) FROM city,state WHERE city.city_name=state.capital);;
SELECT river.river_name FROM river WHERE river.traverse IN (SELECT highlow.state_name FROM highlow WHERE highlow.lowest_elevation= (SELECT min(highlow.lowest_elevation) FROM highlow));;
SELECT city.population FROM city WHERE city.city_name=(SELECT state.capital FROM state WHERE state.state_name='georgia');;
SELECT state.state_name FROM state WHERE state.state_name IN(SELECT border_info.state_name FROM border_info WHERE border_info.border IN(SELECT state.state_name FROM state WHERE state.population=(SELECT max(state.population) FROM state))) AND state.area=(SELECT max(state.area) FROM state WHERE state.state_name IN (SELECT border_info.state_name FROM border_info WHERE border_info.border IN(SELECT state.state_name FROM state WHERE state.population=(SELECT max(state.population) FROM state))));;
SELECT state.population FROM state WHERE state.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT state.state_name FROM state WHERE state.state_name IN (SELECT border_info.border FROM border_info WHERE border_info.state_name = 'texas' ) ORDER BY state.area DESC LIMIT 1;;
SELECT river.river_name FROM river WHERE river.traverse IN(SELECT border_info.border FROM border_info WHERE border_info.state_name='alabama');;
SELECT border_info.border FROM border_info WHERE border_info.state_name IN(SELECT river.traverse FROM river WHERE river.river_name='mississippi');;
SELECT state.capital FROM state,highlow WHERE state.state_name=highlow.state_name AND highlow.highest_elevation=(SELECT max(highlow.highest_elevation) FROM highlow);;
SELECT river.traverse FROM river,state WHERE river.traverse=state.state_name GROUP BY state.state_name ORDER BY count(river.river_name) DESC LIMIT 1 ;;
